name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Akki-8989/infra-repo/.github/workflows/deploy-ui-ecom-app.yml@main
    with:
      repo_name: ui-ecom-app
      infra_repo: infra-repo
    secrets: inherit
